# Generated by Django 3.0.5 on 2020-08-16 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=150, verbose_name='Descritpion')),
                ('production', models.CharField(max_length=50, verbose_name='Production')),
                ('car_class', models.DecimalField(decimal_places=3, help_text='In milimeters', max_digits=9, verbose_name='length')),
                ('body_style', models.CharField(choices=[('two-door', 'Two-door'), ('convertiblee', 'Convertible'), ('three-door', 'Three-door'), ('five-door', 'Five-door')], max_length=15, verbose_name='body_style')),
                ('engine', models.CharField(choices=[('2.0l', '2.0L'), ('2.3l', '2.3L'), ('2.5l', '2.5L')], max_length=10, verbose_name='engine_style')),
                ('transmission', models.CharField(choices=[('2.0l', '2.0L'), ('2.3l', '2.3L'), ('2.5l', '2.5L')], max_length=10, verbose_name='engine_style')),
                ('airconditioning', models.BooleanField(blank=True, default=False, verbose_name='airconditioning')),
                ('length', models.DecimalField(decimal_places=3, help_text='In milimeters', max_digits=9, verbose_name='length')),
                ('width', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='width')),
                ('height', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='height')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=150, verbose_name='Descritpion')),
                ('openair', models.BooleanField(blank=True, default=False, verbose_name='Is open air?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=150, verbose_name='Descritpion')),
                ('image_url', models.URLField(blank=True, default='', verbose_name='Image URL')),
                ('date_come', models.DateTimeField(blank=True, null=True, verbose_name='Timestamp of come to garage')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saabtopia.Car', verbose_name='Type of car')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saabtopia.Place', verbose_name='Place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=150, verbose_name='Descritpion')),
                ('image_url', models.URLField(blank=True, default='', verbose_name='Image URL')),
                ('slug', models.SlugField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='car',
            name='producent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saabtopia.Producent', verbose_name='Producent'),
        ),
        migrations.AddField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
