# Generated by Django 3.0.5 on 2020-08-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saabtopia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_class',
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('5 speed', '5 speed'), ('5 speed sensonic', '5 speed sensonic'), ('4 speed sensonic', '4 speed sensonic')], max_length=18, verbose_name='transmission'),
        ),
    ]
